  input_boolean.trigger_home:
    display_categories: SWITCH
  input_boolean.trigger_sleep:
    display_categories: SWITCH
  input_boolean.trigger_morning:
    display_categories: SWITCH
  input_boolean.trigger_away:
    display_categories: SWITCH
  input_boolean.light_dressing_stay_on:
    display_categories: SWITCH
  input_boolean.heating:
    display_categories: SWITCH
  input_boolean.light_downstairs:
    display_categories: SWITCH
  input_boolean.music_follow:
    display_categories: SWITCH
  input_boolean.visitor:
    display_categories: SWITCH
  switch.smappee_living_room:
    display_categories: LIGHT
  switch.smappee_porch:
    display_categories: LIGHT
  switch.smappee_extra_plug:
    display_categories: LIGHT
  binary_sensor.trigger_template_just_away_kitchen:
    display_categories: MOTION_SENSOR
  binary_sensor.trigger_template_just_home_kitchen:
    display_categories: MOTION_SENSOR
  binary_sensor.trigger_template_just_morning_kitchen:
    display_categories: MOTION_SENSOR
  binary_sensor.trigger_template_just_sleep_kitchen:
    display_categories: MOTION_SENSOR
  binary_sensor.trigger_template_just_morning_dressing:
    display_categories: MOTION_SENSOR
  binary_sensor.trigger_template_just_sleep_dressing:
    display_categories: MOTION_SENSOR
