homeassistant:
  customize: !include customize.yaml
#lovelace in yaml mode
lovelace:

# Start with a default configuration (will start new things when available)
default_config:

# (default)
automation: !include automations.yaml

# (default)
scene: !include scenes.yaml

# (default)
logbook: !include logbook.yaml

# (default)
script: !include scripts.yaml

# (default)
zone: !include zones.yaml

hassio:

sensor: !include sensors.yaml

group: !include groups.yaml



zha:
  zigpy_config:
    ota:
      extra_providers:
       - type: z2m
#      ikea_provider: true                # Auto update Trådfri devices

evohome:
  username: !secret username_evohome
  password: !secret password_evohome
  scan_interval: 120

# Enables Homekit
homekit:
  name: Ons Huisje
  filter: !include homekit_filter.yaml

binary_sensor:
  - platform: template
    sensors:
      bezoek:
        device_class: occupancy
        unique_id: bezoek
        value_template: >-
          {% if is_state("input_boolean.visitor", "on") or is_state("calendar.kuishulp_agenda", "on") or is_state("calendar.babysit_agenda", "on")%}
            on
          {% else %}
            off
          {% endif %}

# Enable Utility meter
utility_meter:
  meter_gas_monthly:
    source: sensor.ons_huisje_sensor_gas
    cycle: monthly
    # Gas
    tariffs:
      - peak
  meter_gas_yearly:
    source: sensor.ons_huisje_sensor_gas
    cycle: yearly
    # Gas
    tariffs:
      - peak
  meter_water_monthly:
    source: sensor.ons_huisje_sensor_water
    cycle: monthly
    # Water
    tariffs:
      - peak
  meter_water_yearly:
    source: sensor.ons_huisje_sensor_water
    cycle: yearly
    # Water
    tariffs:
      - peak

#Used for short term data (recorder is only for 1 week, influxdb wil keep indefintely)
recorder:
  exclude:
    domains:
      - sun
      - binary_sensor
      - calendar
      - device_tracker
      - input_boolean
      - input_datetime
      - input_select
      - input_text
      - sensor
      - switch
      - utility_meter
      - weather
      - zone
    entities:
      - group.computer
      - media_player.spotify_bert_verlinden
      - media_player.this_device
  include:
    domains:
      - automation
      - script
      - climate
      - group
      - light
      - media_player
      - person
      - remote
      - scene
      - vacuum
    entity_globs:
      - binary_sensor.hue_motion_sensor_*_motion
      - binary_sensor.hue_outdoor_sensor_*_motion
      - binary_sensor.ewelink_ds01_*_opening
      - binary_sensor.airco_*_open_window
      - input_boolean.muziek_*
      - sensor.hue_dimmer_switch_*_power
      - sensor.hue_motion_sensor_*_light_level
      - sensor.hue_motion_sensor_*_temperature
      - sensor.hue_motion_sensor_*_power
      - sensor.hue_outdoor_sensor_*_light_level
      - sensor.hue_outdoor_sensor_*_temperature
      - sensor.hue_outdoor_sensor_*_power
      - sensor.airco_*_temperature
      - sensor.home_*_distance
      - sensor.airco_*_humidity
      - sensor.ons_huisje_*
      - sensor.solaredge_*
      - sensor.adguard_*
      - switch.harmony_hub_*
      - switch.hue_smart_plug_*
    entities:
      - binary_sensor.rpi_power_status
      - binary_sensor.remote_ui
      - binary_sensor.bezoek
      - input_boolean.notify_bert
      - input_boolean.notify_caro
      - input_boolean.pre_heat
      - input_boolean.cooling_downstairs
      - input_boolean.cooling_upstairs
      - input_boolean.cooling_attic
      - input_boolean.eve_aqua_ec68
      - input_select.harmony_hub
      - input_select.woning_status
      - sensor.cpu_temperature
      - sensor.dusty_battery_level
      - sensor.disk_use_percent_home
      - sensor.hp_deskjet_3700_series_black_ink
      - sensor.hp_deskjet_3700_series_tri_color_ink
      - sensor.hue_sensor_veranda_light_level
      - sensor.hue_sensor_buiten_temperature
      - sensor.climate_trix_attribute_current_temperature
      - sensor.climate_elmo_attribute_current_temperature
      - sensor.memory_use_percent
      - sensor.meter_gas_monthly_peak
      - sensor.processor_use
      - sensor.template_delta_set_temperature
      - sensor.template_delta_temperature
      - sensor.template_ons_huisje_set_temperature
      - switch.wake_on_lan
      - switch.doorbellback_chime_active
      - switch.doorbellfront_chime_active

#Used for long term data (recorder is only for 1 week, influxdb wil keep indefintely)
influxdb:
  host: a0d7b954-influxdb
  port: !secret port_influxdb
  database: HomeAssistant
  username: !secret username_influxdb
  password: !secret password_influxdb
  max_retries: 3
  default_measurement: state
  include: !include influxdb_filter_include.yaml
  exclude: !include influxdb_filter_exclude.yaml
  component_config:
    sensor.disk_use_percent_home:
      override_measurement: percent
    sensor.memory_use_percent:
      override_measurement: percent
    sensor.processor_use:
      override_measurement: percent
    sensor.ons_huisje_sensor_water:
      override_measurement: m³
    sensor.ons_huisje_sensor_gas:
      override_measurement: m³
  component_config_glob:
    sensor.*temperature:
      override_measurement: celsius
    sensor.temperature*:
      override_measurement: celsius
    sensor.humidity*:
      override_measurement: humidity
    sensor.*humidity:
      override_measurement: humidity
    sensor.*motion:
      override_measurement: state_motion
    light.*:
      override_measurement: state_light
    binary_sensor.*:
      override_measurement: state_binary_sensor
    climate.*:
      override_measurement: celsius
    device_tracker.*:
      override_measurement: state_device_tracker
    group.*:
      override_measurement: state_group
    input_boolean.*:
      override_measurement: state_input_boolean
    input_select.*:
      override_measurement: state_input_select
    person.*:
      override_measurement: state_person
    sun.*:
      override_measurement: state_sun
    switch.*:
      override_measurement: state_switch
    vacuum.*:
      override_measurement: state_vacuum
    weather.*:
      override_measurement: celsius_weather

smappee:
  client_id: !secret client_id_smappee
  client_secret: !secret client_secret_smappee
  
switch:
  - platform: wake_on_lan
    mac: !secret mac_computer_lan
    host: !secret ip_computer_lan
    turn_off:
      service: script.computer_off

# (default) Enables configuration UI
#config:

#(default)
#cloud:

# (default)
#map:

# (default)
#mobile_app:

# (default) Person component
#person:

# (default)
#history:

# (default) Track the sun
#sun:

# (default)
#system_health:

# (default) Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

#(default)
#stream:

#(default)
#logger:
#  default: info
#  logs:
#    homeassistant.core: critical
#    homeassistant.components.zha: debug
#    zigpy: debug

# Text to speech
#tts:
#  - platform: google_translate
#    language: "nl"