homeassistant:
  customize: !include customize.yaml
#lovelace in yaml mode
lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/lovelace-card-tools/card-tools.js
      type: module
    - url: /hacsfiles/lovelace-layout-card/layout-card.js
      type: module
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module

# Start with a default configuration (will start new things when available)
default_config:

# (default)
automation: !include automations.yaml

# (default)
scene: !include scenes.yaml

# (default) Enables configuration UI
config:

# (default) Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# (default)
history: !include history.yaml

# (default)
logbook: !include logbook.yaml

#(default)
cloud:
  alexa:
    entity_config: !include alexa_entity_config.yaml
  google_actions:
    entity_config: !include google_entity_config.yaml

# (default)
map:

# (default)
mobile_app:

# (default) Person component
person:

# (default)
# script: !include_dir_named scripts/
script: !include scripts.yaml

# (default) Track the sun
sun:

# (default)
system_health:

# (default) Allows Home Assistant developers to focus on popular components.
updater:
  # include_used_components: true

# Discover some devices automatically
discovery:

hassio:

ios:
  push:
    categories:
      - name: Bezoeker
        identifier: 'bezoeker'
        actions:
          - identifier: 'RESET_VISITOR'
            title: 'Stuur Babysit naar huis'
            activationMode: 'background'
            authenticationRequired: false
            destructive: true
            behavior: 'default'
          - identifier: 'LEAVE_VISITOR'
            title: 'Babysit blijft nog even'
            activationMode: 'background'
            authenticationRequired: false
            destructive: false
            behavior: 'default'

sensor: !include sensors.yaml

zone: !include zones.yaml

group: !include groups.yaml

ffmpeg:

stream:

evohome:
  username: !secret username_evohome
  password: !secret password_evohome
  scan_interval: 120

logger:
  default: info
  logs:
    homeassistant.core: critical

# Text to speech
notify:
  - platform: alexa_media
    name: alexa_media
  - platform: file
    name: entity_log
    filename: /config/www/entity_log.txt
    timestamp: false

# Enable Mediaplayers
spotify:
  client_id: !secret client_id_spotify
  client_secret: !secret client_secret_spotify


# Enables Homekit
homekit:
  name: Ons Huisje
  auto_start: False
  filter: !include homekit_filter.yaml
  entity_config: !include homekit_entity_config.yaml

binary_sensor:
  - platform: workday
    country: BE
  - platform: template
    sensors:
      trigger_just_away_kitchen:
        value_template: "{{ is_state('input_boolean.trigger_just_away_kitchen', 'on') }}"
      trigger_just_home_kitchen:
        value_template: "{{ is_state('input_boolean.trigger_just_home_kitchen', 'on') }}"
      trigger_just_awake_kitchen:
        value_template: "{{ is_state('input_boolean.trigger_just_awake_kitchen', 'on') }}"
      trigger_just_sleep_kitchen:
        value_template: "{{ is_state('input_boolean.trigger_just_sleep_kitchen', 'on') }}"
      trigger_just_awake_dressing:
        value_template: "{{ is_state('input_boolean.trigger_just_awake_dressing', 'on') }}"
      trigger_just_sleep_dressing:
        value_template: "{{ is_state('input_boolean.trigger_just_sleep_dressing', 'on') }}"

# Enable Utility meter
utility_meter:
  meter_gas_monthly:
    source: sensor.ons_huisje_sensor_gas
    cycle: monthly
    # Gas
    tariffs:
      - peak
  meter_gas_yearly:
    source: sensor.ons_huisje_sensor_gas
    cycle: yearly
    # Gas
    tariffs:
      - peak
  meter_water_monthly:
    source: sensor.ons_huisje_sensor_water
    cycle: monthly
    # Water
    tariffs:
      - peak
  meter_water_yearly:
    source: sensor.ons_huisje_sensor_water
    cycle: yearly
    # Water
    tariffs:
      - peak

recorder:
  purge_keep_days: 7
  commit_interval: 5
  exclude:
    domains:
      - sun
      - automation
      - binary_sensor
      - calendar
      - device_tracker
      - input_boolean
      - input_datetime
      - input_select
      - input_text
      - script
      - sensor
      - switch
      - utility_meter
      - weather
      - zone
    entities:
      - group.computer
      - media_player.nesthub8526
      - media_player.spotify_bert_verlinden
      - media_player.this_device
  include:
    domains:
      - climate
      - group
      - light
      - media_player
      - person
      - remote
      - scene
      - vacuum
    entities:
      - binary_sensor.hue_sensor_dressing_motion
      - binary_sensor.hue_sensor_keuken_motion
      - binary_sensor.hue_sensor_tuin_motion
      - binary_sensor.hue_sensor_tuinhuis_motion
      - binary_sensor.hue_sensor_woonkamer_motion
      - input_boolean.notify_bert
      - input_boolean.notify_caro
      - input_select.harmony_hub
      - input_select.woning_status
      - sensor.aarlo_air_quality_arlo_elmo
      - sensor.aarlo_humidity_arlo_elmo
      - sensor.aarlo_temperature_arlo_elmo
      - sensor.bezoek
      - sensor.climate_badkamer_attribute_current_temperature
      - sensor.climate_dressing_attribute_current_temperature
      - sensor.climate_kamer_elmo_attribute_current_temperature
      - sensor.climate_keuken_attribute_current_temperature
      - sensor.climate_slp_kamer_attribute_current_temperature
      - sensor.climate_veranda_attribute_current_temperature
      - sensor.climate_woonkamer_attribute_current_temperature
      - sensor.cpu_temperature
      - sensor.deurbel_voor_mqtt_battery_sensor
      - sensor.deurbel_voor_mqtt_sensor
      - sensor.disk_use_percent_home
      - sensor.downstairs_nest_protect_battery_health
      - sensor.downstairs_nest_protect_co_status
      - sensor.downstairs_nest_protect_color_status
      - sensor.downstairs_nest_protect_smoke_status
      - sensor.hp_deskjet_3700_series_black_ink
      - sensor.hp_deskjet_3700_series_tri_color_ink
      - sensor.hue_schakelaar_elmos_kamer_battery_level
      - sensor.hue_sensor_dressing_light_level
      - sensor.hue_sensor_dressing_temperature
      - sensor.hue_sensor_keuken_light_level
      - sensor.hue_sensor_keuken_temperature
      - sensor.hue_sensor_tuin_light_level
      - sensor.hue_sensor_tuin_temperature
      - sensor.hue_sensor_tuinhuis_light_level
      - sensor.hue_sensor_tuinhuis_temperature
      - sensor.hue_sensor_veranda_light_level
      - sensor.hue_sensor_woonkamer_light_level
      - sensor.hue_sensor_woonkamer_temperature
      - sensor.memory_use_percent
      - sensor.ons_huisje_always_on_active_power
      - sensor.ons_huisje_always_on_today
      - sensor.ons_huisje_eta
      - sensor.ons_huisje_sensor_gas
      - sensor.ons_huisje_sensor_water
      - sensor.ons_huisje_total_consumption_active_power
      - sensor.ons_huisje_total_consumption_current_hour
      - sensor.ons_huisje_total_consumption_last_5_minutes
      - sensor.ons_huisje_total_consumption_today
      - sensor.processor_use
      - sensor.solaredge_batteries
      - sensor.solaredge_consumption_power
      - sensor.solaredge_current_power
      - sensor.solaredge_energy_this_month
      - sensor.solaredge_energy_this_month_template
      - sensor.solaredge_energy_this_year
      - sensor.solaredge_energy_this_year_template
      - sensor.solaredge_energy_today
      - sensor.solaredge_energy_today_template
      - sensor.solaredge_exported_power
      - sensor.solaredge_gateways
      - sensor.solaredge_grid_power
      - sensor.solaredge_imported_power
      - sensor.solaredge_inverters
      - sensor.solaredge_lifetime_energy
      - sensor.solaredge_lifetime_energy_template
      - sensor.solaredge_meters
      - sensor.solaredge_power_consumption
      - sensor.solaredge_production_power
      - sensor.solaredge_selfconsumption_power
      - sensor.solaredge_sensors
      - sensor.solaredge_site_details
      - sensor.solaredge_solar_power
      - sensor.solaredge_storage_level
      - sensor.solaredge_storage_power
      - sensor.template_delta_set_temperature
      - sensor.template_delta_temperature
      - sensor.template_ons_huisje_set_temperature
      - sensor.upstairs_nest_protect_battery_health
      - sensor.upstairs_nest_protect_co_status
      - sensor.upstairs_nest_protect_color_status
      - sensor.upstairs_nest_protect_smoke_status
      - switch.adguard_filtering
      - switch.adguard_parental_control
      - switch.adguard_protection
      - switch.adguard_safe_browsing
      - switch.adguard_safe_search
      - switch.harmony_hub_alexa
      - switch.harmony_hub_apple_tv
      - switch.harmony_hub_nintendo_switch
      - switch.harmony_hub_tv_decoder
      - switch.harmony_hub_webos
      - switch.wake_on_lan

influxdb:
  host: a0d7b954-influxdb
  port: !secret port_influxdb
  database: HomeAssistant
  username: !secret username_influxdb
  password: !secret password_influxdb
  max_retries: 3
  default_measurement: state
  include: !include influxdb_filter_include.yaml
  exclude: !include influxdb_filter_exclude.yaml
  component_config:
    sensor.disk_use_percent_home:
      override_measurement: percent
    sensor.memory_use_percent:
      override_measurement: percent
    sensor.processor_use:
      override_measurement: percent
    sensor.ons_huisje_sensor_water:
      override_measurement: m³
    sensor.ons_huisje_sensor_gas:
      override_measurement: m³
  component_config_glob:
    sensor.*temperature:
      override_measurement: celsius
    sensor.temperature*:
      override_measurement: celsius
    sensor.humidity*:
      override_measurement: humidity
    sensor.*humidity:
      override_measurement: humidity
    sensor.*motion:
      override_measurement: state_motion
    light.*:
      override_measurement: state_light
    binary_sensor.*:
      override_measurement: state_binary_sensor
    climate.*:
      override_measurement: celsius
    device_tracker.*:
      override_measurement: state_device_tracker
    group.*:
      override_measurement: state_group
    input_boolean.*:
      override_measurement: state_input_boolean
    input_select.*:
      override_measurement: state_input_select
    person.*:
      override_measurement: state_person
    sun.*:
      override_measurement: state_sun
    switch.*:
      override_measurement: state_switch
    vacuum.*:
      override_measurement: state_vacuum
    weather.*:
      override_measurement: celsius_weather

weather:
  - platform: darksky
    api_key: !secret api_key_darksky
    mode: daily

#aarlo:
#  username: !secret username_arlo_2
#  password: !secret password_arlo_2
#  refresh_devices_every: 2
#  stream_timeout: 120

nest:
  client_id: !secret client_id_nest
  client_secret: !secret client_secret_nest

solaredge:
  api_key: !secret api_key_solar_edge
  site_id: !secret client_id_solar_edge

smappee:
  client_id: !secret client_id_smappee
  client_secret: !secret client_secret_smappee
#  host: !secret ip_smappee
#  username: !secret username_smappee
#  password: !secret password_smappee

# USED FOR CONNECTING TO CALENDARS
google:
  client_id: !secret client_id_google
  client_secret: !secret client_secret_google
  track_new_calendar: False

light:
  - platform: limitlessled
    bridges:
    - host: !secret ip_milight_bridge_1
      groups:
      - number: 1
        type: bridge-led
        name: milight_woonkamer_bridge
    - host: !secret ip_milight_bridge_2
      groups:
      - number: 1
        type: bridge-led
        name: milight_keuken_bridge
      - number: 1
        type: rgbww
        name: milight_keuken
      - number: 2
        type: rgbww
        name: milight_badkamer
  - platform: aarlo
  
switch:
  - platform: wake_on_lan
    mac: !secret mac_computer_lan
    host: !secret ip_computer_lan
    turn_off:
      service: script.computer_off

# OLD COMPONENTS
#hacs:
#  token: !secret api_key_hacs
#  appdaemon: False
#  python_script: False

#emulated_hue:
#  host_ip: !secret ip_homeassistant
#  expose_by_default: false
#  off_maps_to_on_domains:
#    - script
#  exposed_domains:
#    - switch
#    - light
#    - input_boolean
#  entities: !include emulated_hue_entity_config.yaml

#hue:
#  bridges:
#    host: !secret ip_hue
#    allow_unreachable: true
#    allow_hue_groups: false

#vacuum:
#  - platform: roomba
#    host: !secret ip_irobot
#    username: !secret username_irobot
#    password: !secret password_irobot
#    name: Dusty
#    continuous: true