homeassistant:
  customize: !include_dir_merge_named customize/
  customize_domain: !include_dir_merge_named customize_domains/

#lovelace in yaml mode
lovelace:
  mode: yaml

# Start with a default configuration (will start new things when available)
default_config:

# (default)
automation: !include automations.yaml
automation old: !include_dir_merge_list automations/

# (default) Enables configuration UI
config:

# (default) Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# (default) Enables the frontend (default)
frontend:
  javascript_version: latest

# (default)
history: !include history.yaml

# (default)
logbook: !include logbook.yaml

#(default)
cloud:
  alexa:
    entity_config: !include alexa_entity_config.yaml
  google_actions:
    entity_config: !include google_entity_config.yaml

# (default)
map:

# (default)
mobile_app:

# (default) Person component
person:

# (default)
script: !include_dir_named scripts/

# (default) Track the sun
sun:

# (default)
system_health:

# (default) Allows Home Assistant developers to focus on popular components.
updater:
  # include_used_components: true

# Discover some devices automatically
discovery:
  ignore:
    - plex_mediaserver

hassio:

ios:
  push:
    categories:
      - name: Bezoeker
        identifier: 'bezoeker'
        actions:
          - identifier: 'RESET_VISITOR'
            title: 'Stuur Babysit naar huis'
            activationMode: 'background'
            authenticationRequired: false
            destructive: true
            behavior: 'default'
          - identifier: 'LEAVE_VISITOR'
            title: 'Babysit blijft nog even'
            activationMode: 'background'
            authenticationRequired: false
            destructive: false
            behavior: 'default'

sensor: !include sensors.yaml

zone: !include zones.yaml

group: !include groups.yaml

input_boolean: !include input_booleans.yaml

input_select: !include input_selects.yaml

evohome:
  username: !secret username_evohome
  password: !secret password_evohome
  scan_interval: 120

logger:
  default: warning
  logs:
    homeassistant.core: critical
#    custom_components.alexa_media: debug
#    alexapy: debug

# CUSTOM COMPONENTS
hacs:
  token: !secret api_key_hacs
  appdaemon: False
  python_script: False

# Text to speech
notify:
  - platform: alexa_media
    name: alexa_media

# Enables Homekit
homekit:
  auto_start: False
  filter: !include homekit_filter.yaml
  entity_config: !include homekit_entity_config.yaml

binary_sensor:
  - platform: template
    sensors:
      trigger_just_away_kitchen:
        device_class: motion
        entity_id:
          - input_boolean.trigger_just_away_kitchen
        value_template: "{{ is_state('input_boolean.trigger_just_away_kitchen', 'on') }}"
      trigger_just_home_kitchen:
        device_class: motion
        entity_id:
          - input_boolean.trigger_just_home_kitchen
        value_template: "{{ is_state('input_boolean.trigger_just_home_kitchen', 'on') }}"
      trigger_just_awake_kitchen:
        device_class: motion
        entity_id:
          - input_boolean.trigger_just_awake_kitchen
        value_template: "{{ is_state('input_boolean.trigger_just_awake_kitchen', 'on') }}"
      trigger_just_sleep_kitchen:
        device_class: motion
        entity_id:
          - input_boolean.trigger_just_sleep_kitchen
        value_template: "{{ is_state('input_boolean.trigger_just_sleep_kitchen', 'on') }}"
      trigger_just_awake_dressing:
        device_class: motion
        entity_id:
          - input_boolean.trigger_just_awake_dressing
        value_template: "{{ is_state('input_boolean.trigger_just_awake_dressing', 'on') }}"
      trigger_just_sleep_dressing:
        device_class: motion
        entity_id:
          - input_boolean.trigger_just_sleep_dressing
        value_template: "{{ is_state('input_boolean.trigger_just_sleep_dressing', 'on') }}"

# Enable Utility meter
utility_meter:
  template_elektricity_daily_usage_daily:
    source: sensor.template_elektricity_daily_usage
    cycle: daily
    tariffs:
      - peak
  template_elektricity_daily_usage_monthly:
    source: sensor.template_elektricity_daily_usage
    cycle: monthly
    tariffs:
      - peak
  solaredge_energy_this_month_monthly:
    source: sensor.solaredge_energy_this_month_template
    cycle: monthly
    tariffs:
      - peak
  smappee_ons_huisje_power_today_monthly:
    source: sensor.smappee_ons_huisje_power_today
    cycle: monthly
    tariffs:
      - peak
  smappee_ons_huisje_water_sensor_2_monthly:
    source: sensor.smappee_ons_huisje_water_sensor_2_template
    cycle: monthly
    tariffs:
      - peak
  smappee_ons_huisje_water_sensor_1_monthly:
    source: sensor.smappee_ons_huisje_water_sensor_1_template
    cycle: monthly
    tariffs:
      - peak

recorder:
  purge_keep_days: 3
  purge_interval: 1

influxdb:
  host: a0d7b954-influxdb
  port: !secret port_influxdb
  database: HomeAssistant
  username: !secret username_influxdb
  password: !secret password_influxdb
  max_retries: 3
  default_measurement: state
  include: !include influxdb_filter_include.yaml
  exclude: !include influxdb_filter_exclude.yaml

weather:
  - platform: darksky
    api_key: !secret api_key_darksky
    mode: daily

mqtt:
  broker: core-mosquitto
  username: !secret username_mqtt
  password: !secret password_mqtt

arlo:
  username: !secret username_arlo
  password: !secret password_arlo

nest:
  client_id: !secret client_id_nest
  client_secret: !secret client_secret_nest

solaredge:
  api_key: !secret api_key_solar_edge
  site_id: !secret client_id_solar_edge

unifi:
  controllers:
    - host: Default
      site: Our home
      detection_time: 240

vacuum:
  - platform: roomba
    host: !secret ip_irobot
    username: !secret username_irobot
    password: !secret password_irobot
    name: Dusty
    continuous: true

media_player:
  - platform: samsungtv
    name: Samsung TV
    host: !secret ip_tv
    mac: !secret mac_tv
  - platform: spotify
    client_id: !secret client_id_spotify
    client_secret: !secret client_secret_spotify

smappee:
  host: !secret ip_smappee
  client_id: !secret client_id_smappee
  client_secret: !secret client_secret_smappee
  username: !secret username_smappee
  password: !secret password_smappee

# USED FOR CONNECTING TO CALENDARS
google:
  client_id: !secret client_id_google
  client_secret: !secret client_secret_google
  track_new_calendar: False

#emulated_hue:
#  host_ip: !secret ip_homeassistant
#  expose_by_default: false
#  off_maps_to_on_domains:
#    - script
#  exposed_domains:
#    - switch
#    - light
#    - input_boolean
#  entities: !include emulated_hue_entity_config.yaml

hue:
  bridges:
    host: !secret ip_hue
    allow_unreachable: true
    allow_hue_groups: false

light:
  platform: limitlessled
  bridges:
    - host: !secret ip_milight_bridge_1
      groups:
      - number: 1
        type: bridge-led
        name: milight_woonkamer_bridge
    - host: !secret ip_milight_bridge_2
      groups:
      - number: 1
        type: bridge-led
        name: milight_keuken_bridge
      - number: 1
        type: rgbww
        name: milight_keuken
      - number: 2
        type: rgbww
        name: milight_badkamer

switch:
  - platform: wake_on_lan
    mac: !secret mac_computer_lan
    host: !secret ip_computer_lan
    turn_off:
      service: script.remote_kitchen_pc_off
