# CONFIGURATION FOR GOOGLE ENTITIES
# LIGHTS
# MILIGHTS

light.lightstrip_woonkamer_tv:
  name: Woonkamer Tv Licht
  room: Woonkamer
light.milight_keuken_bridge:
  name: Keuken Tv Licht
  room: Keuken
light.lightstrip_keuken:
  name: Keuken Licht
  room: Keuken
light.lightstrip_badkamer:
  name: Badkamer Licht
  room: Badkamer

# HUE LIGHTS

light.hue_light_veranda:
  name: Veranda Lamp
  room: Veranda
light.hue_light_kamer_elmo_one:
  name: Elmo's Staanlamp
  room: Elmo's Kamer
light.hue_light_kamer_elmo_two:
  name: Elmo's Lamp
  room: Elmo's Kamer
light.hue_light_woonkamer:
  name: Woonkamer Lamp
  room: Woonkamer
light.hue_light_dressing_one:
  name: Dressing Lamp 1
  room: Dressing
light.hue_light_dressing_two:
  name: Dressing Lamp 2
  room: Dressing
light.hue_light_dressing_three:
  name: Dressing Lamp 3
  room: Dressing

# HUE SMART PLUGS

switch.hue_smart_plug_veranda:
  name: Veranda Licht Strip
  room: Veranda
switch.hue_smart_plug_woonkamer_two:
  name: Woonkamer Spacewalker
  room: Woonkamer
switch.hue_smart_plug_woonkamer_one:
  name: Woonkamer Licht Strip
  room: Woonkamer
switch.hue_smart_plug_eetkamer:
  name: Extra Plug
  room: Woning

# MEDIA PLAYERS

media_player.apple_tv_keuken:
  name: Apple TV HD
  room: keuken

media_player.apple_tv_woonkamer:
  name: Apple TV 4K
  room: Woonkamer

# CLIMATE

climate.badkamer:
  name: Badkamer
  room: Badkamer

climate.dressing:
  name: Dressing
  room: Dressing

climate.kamer_elmo:
  name: Elmo's Kamer
  room: Elmo's Kamer

climate.keuken:
  name: Keuken
  room: Keuken

climate.ons_huisje:
  name: Evohome
  room: Woning

climate.slp_kamer:
  name: Slaapkamer
  room: Slaapkamer

climate.woonkamer:
  name: Woonkamer
  room: Woonkamer

# SWITCHES

switch.wake_on_lan:
  name: Computer
  aliases:
    - PC
    - Kitchen PC
  room: Keuken

# INPUT BOOLEANS

input_boolean.light_downstairs:
  name: Alle Lichten Beneden
  aliases:
    - All Lights Downstairs
  room: Woning
input_boolean.visitor:
  name: Bezoeker
  aliases:
    - Visitor
    - Bezoek
  room: Woning
input_boolean.music_follow:
  name: Muziek Volgen
  aliases:
    - Music Follows
  room: Woning
input_boolean.heating:
  name: Verwarming Volgen
  aliases:
    - Verwarming Volgt
    - Heating Shedule
  room: Woning

# VACUUM

vacuum.dusty:
  name: Dusty
  room: Woonkamer