# CONFIGURATION FOR HOMEKIT ENTITIES
# LIGHTS

light.milight_keuken_bridge:
  name: Keuken Tv Lampje

light.lightstrip_woonkamer_tv:
  name: Woonkamer Tv Lampje
light.lightstrip_keuken:
  name: Keuken LED Strip
light.lightstrip_badkamer:
  name: Badkamer LED Strip

light.hue_light_veranda:
  name: Veranda Flos Arco
light.hue_light_kamer_elmo_one:
  name: Kamer van Elmo Staanlamp
light.hue_light_kamer_elmo_two:
  name: Kamer van Elmo Lamp
light.hue_light_woonkamer:
  name: Woonkamer Lamp
light.hue_light_dressing_one:
  name: Dressing Lamp 1
light.hue_light_dressing_two:
  name: Dressing Lamp 2
light.hue_light_dressing_three:
  name: Dressing Lamp 3

light.hue_light_tuin_one:
  name: Tuin Lamp 1
light.hue_light_tuin_two:
  name: Tuin Lamp 2
light.hue_light_tuin_three:
  name: Tuin Lamp 3
light.hue_light_tuin_four:
  name: Tuin Lamp 4
light.hue_light_tuin_five:
  name: Tuin Lamp 5
light.hue_light_tuin_six:
  name: Tuin Lamp 6
light.hue_light_tuinhuis:
  name: Tuinhuis LED Strip

# SWITCHES

switch.wake_on_lan:
  name: Keuken Computer
  type: switch
switch.adguard_protection:
  name: Ons Huisje Protection
switch.adguard_filtering:
  name: Ons Huisje Filtering
switch.adguard_parental_control:
  name: Ons Huisje Parental Control

switch.hue_smart_plug_veranda:
  name: Veranda LED Lichtjes
switch.hue_smart_plug_woonkamer_two:
  name: Woonkamer Spacewalker
switch.hue_smart_plug_woonkamer_one:
  name: Woonkamer LED Lichtjes
switch.hue_smart_plug_eetkamer:
  name: Extra Plug
switch.hue_smart_plug_five:
  name: Kamer van Trix Camera van Trix
switch.hue_smart_plug_six:
  name: Kamer van Elmo Camera van Elmo


# INPUT SELECT

input_select.harmony_hub:
  name: Woonkamer Harmony
input_select.woning_status:
  name: Ons Huisje Status

# INPUT BUTTON

input_button.wake_elmo:
  name: Kamer van Elmo Maak Elmo Wakker

# INPUT BOOLEANS

input_boolean.vacuum_clean_today:
  name: Ons Huisje Dusty Kuisen
input_boolean.keep_computer_on:
  name: Keuken PC Altijd Aan
input_boolean.light_downstairs:
  name: Ons Huisje Licht Sensors
input_boolean.visitor:
  name: Ons Huisje Bezoek
input_boolean.trigger_home:
  name: Ons Huisje Thuis
input_boolean.trigger_sleep:
  name: Ons Huisje Slapen
input_boolean.trigger_morning:
  name: Ons Huisje Ochtend
input_boolean.trigger_away:
  name: Ons Huisje Weg
input_boolean.music_follow:
  name: Ons Huisje Alexa
input_boolean.light_dressing_stay_on:
  name: Dressing Licht Aanhouden
input_boolean.light_garden_stay_on:
  name: Tuin Licht Aanhouden
input_boolean.elmo_wekker:
  name: Kamer van Elmo Wekker
input_boolean.pre_heat:
  name: Ons Huisje Pre-Heat

# SENSORS MOTION

binary_sensor.hue_sensor_keuken_motion:
  name: Keuken Beweging
binary_sensor.hue_sensor_dressing_motion:
  name: Dressing Beweging
binary_sensor.hue_sensor_woonkamer_motion:
  name: Woonkamer Beweging
binary_sensor.hue_sensor_tuin_motion:
  name: Tuin Beweging
binary_sensor.hue_sensor_tuinhuis_motion:
  name: Tuinhuis Beweging
binary_sensor.hue_sensor_terras_motion:
  name: Terras Beweging

# SENORS LIGHT LEVEL

sensor.hue_sensor_keuken_light_level:
  name: Keuken Lichtniveau
sensor.hue_sensor_dressing_light_level:
  name: Dressing Lichtniveau
sensor.hue_sensor_woonkamer_light_level:
  name: Woonkamer Lichtniveau
sensor.hue_sensor_tuin_light_level:
  name: Tuin Lichtniveau
sensor.hue_sensor_tuinhuis_light_level:
  name: Tuinhuis Lichtniveau
sensor.hue_sensor_terras_light_level:
  name: Terras Lichtniveau

# CLIMATE

climate.slp_kamer:
  name: Kamer van Trix Thermostaat
climate.badkamer:
  name: Badkamer Thermostaat
climate.kamer_elmo:
  name: Kamer van Elmo Thermostaat
climate.zolder:
  name: Slaapkamer Thermostaat
climate.keuken:
  name: Keuken Thermostaat
climate.woonkamer:
  name: Woonkamer Thermostaat
climate.ons_huisje:
  name: Ons Huisje Thermostaat
sensor.hue_sensor_tuin_temperature:
  name: Tuin Temperatuur
sensor.hue_sensor_tuinhuis_temperature:
  name: Tuinhuis Temperatuur
sensor.hue_sensor_terras_temperature:
  name: Terras Temperatuur

# VACUUM

vacuum.dusty:
  name: Ons Huisje Dusty

# DEVICE TRACKERS

device_tracker.router_iphone_bert:
  name: Bert
device_tracker.router_iphone_caro:
  name: Caroline