# CONFIGURATION FOR HOMEKIT ENTITIES
# LIGHTS

light.milight_woonkamer_bridge:
  name: Woonkamer Tv Lampje
light.milight_keuken_bridge:
  name: Keuken Tv Lampje
light.milight_keuken:
  name: Keuken LED Strip
light.milight_badkamer:
  name: Badkamer LED Strip

light.hue_light_veranda:
  name: Veranda Flos Arco
light.hue_light_kamer_elmo_one:
  name: Elmo's Kamer Staanlamp
light.hue_light_kamer_elmo_two:
  name: Elmo's Kamer Lamp
light.hue_light_woonkamer:
  name: Woonkamer Lamp
light.hue_light_dressing_one:
  name: Dressing Lamp 1
light.hue_light_dressing_two:
  name: Dressing Lamp 2
light.hue_light_dressing_three:
  name: Dressing Lamp 3

light.hue_smart_plug_veranda:
  name: Veranda LED Lichtjes
light.hue_smart_plug_woonkamer_two:
  name: Woonkamer Spacewalker
light.hue_smart_plug_woonkamer_one:
  name: Woonkamer LED Lichtjes
light.hue_smart_plug_extra:
  name: Extra Plug

# INPUT SELECT

input_select.harmony_hub:
  name: TV

# SWITCHES

switch.wake_on_lan:
  name: Keuken Computer
  type: switch

# INPUT BOOLEANS

input_boolean.light_downstairs:
  name: Ons Huisje Licht Beneden
input_boolean.visitor:
  name: Ons Huisje Bezoek
input_boolean.heating:
  name: Ons Huisje Verwarming Schema
input_boolean.trigger_home:
  name: Ons Huisje Thuis
input_boolean.trigger_sleep:
  name: Ons Huisje Slapen
input_boolean.trigger_morning:
  name: Ons Huisje Ochtend
input_boolean.trigger_away:
  name: Ons Huisje Weg
input_boolean.music_follow:
  name: Ons Huisje Muziek Volgen
input_boolean.light_dressing_stay_on:
  name: Dressing Licht Aanhouden

# SENSORS

binary_sensor.hue_sensor_keuken_motion:
  name: Keuken Beweging
sensor.hue_sensor_keuken_light_level:
  name: Keuken Lichtniveau
binary_sensor.hue_sensor_dressing_motion:
  name: Dressing Beweging
sensor.hue_sensor_dressing_light_level:
  name: Dressing Lichtniveau
binary_sensor.hue_sensor_woonkamer_motion:
  name: Woonkamer Beweging
sensor.hue_sensor_woonkamer_light_level:
  name: Woonkamer Lichtniveau

# CLIMATE

climate.slp_kamer:
  name: Slaapkamer Temperatuur
climate.badkamer:
  name: Badkamer Temperatuur
climate.kamer_elmo:
  name: Elmo's Kamer Temperatuur
climate.keuken:
  name: Keuken Temperatuur
climate.woonkamer:
  name: Woonkamer Temperatuur
climate.ons_huisje:
  name: Ons Huisje Temperatuur

# VACUUM

script.dusty_on:
  name: Veranda Dusty Start
script.dusty_off:
  name: Veranda Dusty Stop
input_boolean.vacuum_clean_today:
  name: Veranda Dusty klaar

# DEVICE TRACKERS

device_tracker.router_iphone_bert:
  name: Bert
device_tracker.router_iphone_caro:
  name: Caroline
