# CUSTOM SENSOR AFVAL

- platform: afvalbeheer
  wastecollector: RecycleApp
  resources:
    - restafval
    - papier
    - pmd
    - glas 
  postcode: !secret zone_home_postcode
  streetname: !secret zone_home_streetname
  streetnumber: !secret zone_home_housenumber
  dateformat: '%Y-%m-%d'
  dateonly: 1
  dutch: 1
  builtinicons: 1

# SENSORS TO CALCULATE MIN AND MAX FOR OUTSIDE TEMPERATURE

- platform: min_max
  unique_id: hue_sensor_buiten_temperature
  type: min
  name: hue_sensor_buiten_temperature
  entity_ids:
  - sensor.hue_outdoor_sensor_3_temperature
  - sensor.hue_outdoor_sensor_1_temperature
  - sensor.hue_outdoor_sensor_2_temperature

# SENSOR TO CHECK STATE OF RASPBERRY PI

#- platform: systemmonitor
#  resources:
#    - type: disk_use_percent
#      arg: /home
#    - type: memory_use_percent
#    - type: processor_use
#    - type: last_boot

# SENSOR TO USE DATE AND TIME

- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
