# CUSTOMIZATION FOR ALL AUTOMATIONS

  automation:
#    friendly_name: friendly name
#    homebridge_name: homebridge name (see homekit_entity_config)
#    hidden: false
#    homebridge_hidden: false (see homekit_filter)
#    emulated_hue_hidden: false (deprecated see configuration file)
#    icon: mdi:home
#    assumed_state: true
#    device_class: None (only for Binary Sensor, Sensor, Cover)
#    unit_of_measurement: None
    initial_state: 'on'
