# AUTOMATIONS FOR RADIO (ACTION = SCRIPT)

# PLAY RADIO DOWNSTAIRS

- alias: Muziek - Radio - Play Downstairs 2
  trigger:
  - platform: state
    to: 'playing'
    entity_id:
      - media_player.livingroom_alexa
      - media_player.kitchen_alexa_1
  condition:
  - condition: template
    value_template: "{{ states('media_player.livingroom_alexa') in ['playing'] }}"
  - condition: template
    value_template: "{{ states('media_player.kitchen_alexa_1') in ['playing'] }}"
  - condition: template
    value_template: "{{ states('media_player.downstairs') not in ['playing'] }}"
  - condition: template
    value_template: "{{ states('media_player.everywhere') not in ['playing'] }}"
  action:
  - service: script.turn_on
    entity_id:
      - script.music_play_downstairs

- alias: Muziek - Radio - Play Downstairs 1
  trigger:
  - platform: state
    entity_id: binary_sensor.living_sensor_motion
    from: 'off'
    to: 'on'
  condition:
  - condition: time
    after: !secret radio_on
    before: !secret radio_off
  - condition: state
    entity_id: input_boolean.music_follow
    state: 'on'
  - condition: state
    entity_id: input_boolean.plex_kitchen
    state: 'off'
  - condition: state
    entity_id: input_boolean.plex_livingroom
    state: 'off'
  - condition: template
    value_template: "{{ states('input_select.woning_status') in ['Juist Thuis', 'Juist Wakker', 'Thuis', 'Thuis (Werk)', 'Thuis (Verlof)'] }}"
  - condition: template
    value_template: "{{ states('input_select.harmony_hub') in ['Powered Off', 'Alexa'] }}"
  - condition: template
    value_template: "{{ states('media_player.livingroom_alexa') not in ['playing'] }}"
  - condition: template
    value_template: "{{ states('media_player.downstairs') not in ['playing'] }}"
  - condition: template
    value_template: "{{ states('media_player.everywhere') not in ['playing'] }}"
  action:
  - service: script.turn_on
    entity_id:
      - script.music_play_downstairs

- alias: Muziek - Radio - Stop Downstairs
  trigger:
  - entity_id: binary_sensor.living_sensor_motion
    for:
      minutes: 15
    platform: state
    to: 'off'
  condition:
  - condition: template
    value_template: "{{ states('media_player.downstairs') in ['playing'] }}"
  action:
  - service: script.turn_on
    entity_id:
      - script.music_stop_downstairs

# PLAY RADIO IN LIVING ROOM

- alias: Muziek - Radio - Woonkamer
  trigger:
  - platform: state
    entity_id: input_select.harmony_hub
  condition:
  - condition: template
    value_template: "{{ (states('media_player.livingroom_alexa') in ['playing'] and states('input_select.harmony_hub') not in ['Alexa']) or (states('media_player.livingroom_alexa') not in ['playing'] and states('media_player.downstairs') not in ['playing'] and states('media_player.everywhere') not in ['playing'] and states('input_select.harmony_hub') in ['Alexa']) }}"
  action:
  - service: script.turn_on
    data_template:
      entity_id: >
        {%- if states('media_player.livingroom_alexa') not in ['playing'] and states('media_player.downstairs') not in ['playing'] and states('media_player.everywhere') not in ['playing'] and states('input_select.harmony_hub') in ['Alexa'] -%}
          script.music_play_living_room
        {%- elif states('media_player.livingroom_alexa') in ['playing'] and states('input_select.harmony_hub') not in ['Alexa'] -%}
          script.music_stop_living_room
        {%- else -%}
          script.empty
        {%- endif %}

# PLAY RADIO IN BATHROOM

- alias: Muziek - Radio - Play Badkamer
  trigger:
  - entity_id: binary_sensor.dressing_sensor_motion
    platform: state
    from: 'off'
    to: 'on'
  condition:
  - condition: time
    after: !secret radio_on
    before: !secret radio_off
  - condition: state
    entity_id: input_boolean.music_follow
    state: 'on'
  - condition: template
    value_template: "{{ states('input_select.woning_status') in ['Juist Wakker', 'Thuis', 'Thuis (Werk)', 'Thuis (Verlof)'] }}"
  - condition: template
    value_template: "{{ states('media_player.bathroom_alexa') not in ['playing'] }}"
  - condition: template
    value_template: "{{ states('media_player.upstairs') not in ['playing'] }}"
  - condition: template
    value_template: "{{ states('media_player.everywhere') not in ['playing'] }}"
  action:
  - service: script.turn_on
    entity_id:
      - script.music_play_bathroom

- alias: Muziek - Radio - Stop Badkamer
  trigger:
  - entity_id: binary_sensor.dressing_sensor_motion
    for:
      minutes: 30
    platform: state
    to: 'off'
  condition:
  - condition: template
    value_template: "{{ states('media_player.bathroom_alexa') in ['playing'] }}"
  action:
  - service: script.turn_on
    entity_id:
      - script.music_stop_bathroom

# PLAY RADIO IN KITCHEN

- alias: Muziek - Radio - Play Keuken
  trigger:
  - platform: state
    entity_id:
      - input_boolean.plex_kitchen
    to: 'off'
    for:
      minutes: 1
  - platform: template
    value_template: "{{ states('input_select.harmony_hub') in ['Powered Off', 'Alexa'] }}"
  - platform: state
    entity_id: binary_sensor.keuken_sensor_motion
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: input_boolean.music_follow
    from: 'off'
    to: 'on'
  condition:
  - condition: time
    after: !secret radio_on
    before: !secret radio_off
  - condition: state
    entity_id: binary_sensor.keuken_sensor_motion
    state: 'on'
  - condition: state
    entity_id: input_boolean.music_follow
    state: 'on'
  - condition: state
    entity_id: input_boolean.plex_kitchen
    state: 'off'
  - condition: state
    entity_id: input_boolean.plex_livingroom
    state: 'off'
  - condition: template
    value_template: "{{ states('input_select.woning_status') in ['Juist Thuis', 'Juist Wakker', 'Thuis', 'Thuis (Werk)', 'Thuis (Verlof)'] }}"
  - condition: template
    value_template: "{{ states('input_select.harmony_hub') in ['Powered Off', 'Alexa'] }}"
  - condition: template
    value_template: "{{ states('media_player.kitchen_alexa_1') not in ['playing'] }}"
  - condition: template
    value_template: "{{ states('media_player.downstairs') not in ['playing'] }}"
  - condition: template
    value_template: "{{ states('media_player.everywhere') not in ['playing'] }}"
  action:
  - service: script.turn_on
    entity_id:
      - script.music_play_kitchen
  - delay: '00:10:00'

- alias: Muziek - Radio - Stop Keuken
  trigger:
  - entity_id: binary_sensor.keuken_sensor_motion
    for:
      minutes: 60
    platform: state
    to: 'off'
  - platform: template
    value_template: "{{ states('input_select.harmony_hub') in ['Tv Decoder', 'Web OS', 'Apple Tv'] }}"
  - platform: state
    entity_id:
      - input_boolean.plex_kitchen
      - input_boolean.plex_livingroom
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.music_follow
    state: 'on'
  - condition: template
    value_template: "{{ states('media_player.kitchen_alexa_1') in ['playing'] }}"
  action:
  - service: script.turn_on
    entity_id:
      - script.music_stop_kitchen

# TEMPORARY DISABLE MUSIC FOLLOW

- alias: Muziek - Radio - Temporary disable music follow
  trigger:
  - entity_id: media_player.kitchen_alexa_1
    platform: state
    from: 'playing'
    to: 'paused'
  condition:
  - condition: or
    conditions:
      - condition: state
        entity_id: media_player.downstairs
        state: 'paused'
        for:
          minutes: 5
      - condition: state
        entity_id: media_player.downstairs
        state: 'standby'
        for:
          minutes: 5
      - condition: state
        entity_id: media_player.downstairs
        state: 'unavailable'
        for:
          minutes: 5
  - condition: state
    entity_id: input_boolean.music_follow
    state: 'on'
  - condition: state
    entity_id: input_boolean.plex_kitchen
    state: 'off'
  - condition: state
    entity_id: input_boolean.plex_livingroom
    state: 'off'
  - condition: template
    value_template: "{{ states('input_select.woning_status') not in ['Juist Weg', 'Weg', 'Slapen'] }}"
  action:
    - service: script.turn_on
      entity_id:
        - script.music_follow_disable
        - script.music_stop_kitchen

- alias: Muziek - Radio - Follow Enable
  trigger:
  - entity_id: media_player.kitchen_alexa_1
    platform: state
    from: 'paused'
    to: 'playing'
  - entity_id: input_boolean.music_follow
    platform: state
    to: 'off'
    for:
      minutes: 4
  condition:
  - condition: state
    entity_id: media_player.kitchen_alexa_1
    state: 'playing'
  - condition: state
    entity_id: input_boolean.music_follow
    state: 'off'
    for:
      minutes: 3
  action:
  - service: script.turn_on
    entity_id:
      - script.music_follow_enable

- alias: Muziek - Radio - Follow Enable 2
  trigger:
  - entity_id: input_boolean.music_follow
    platform: state
    to: 'off'
    for:
      minutes: 180
  condition:
  action:
  - service: script.turn_on
    entity_id:
      - script.music_follow_enable

# RADIO VOLUME

- alias: Muziek - Radio - Volume wanneer Living Room
  trigger:
  - platform: template
    value_template: "{{ states('input_select.harmony_hub') in ['Alexa'] }}"
  - platform: state
    to: 'playing'
    entity_id:
      - media_player.livingroom_alexa
      - media_player.downstairs
      - media_player.everywhere
  action:
  - service: script.turn_on
    entity_id:
      - script.music_volume_living_room

- alias: Muziek - Radio - Volume wanneer beiden thuis
  trigger:
  - platform: state
    to: home
    entity_id:
      - person.bert
      - person.caroline
  condition:
  - condition: state
    entity_id: person.bert
    state: 'home'
  - condition: state
    entity_id: person.caroline
    state: 'home'
  action:
  - service: script.turn_on
    entity_id:
      - script.music_volume_kitchen
      - script.music_volume_living_room
      - script.music_volume_bathroom
