# AUTOMATIONS FOR RADIO (ACTION = SCRIPT)

# PLAY RADIO DOWNSTAIRS

- alias: Muziek - Downstairs - Play 2
  trigger:
  - platform: state
    to: 'playing'
    entity_id:
      - media_player.alexa_livingroom_1
      - media_player.alexa_kitchen_1
  condition:
  - condition: template
    value_template: "{{ states('media_player.alexa_livingroom_1') in ['playing'] }}"
  - condition: template
    value_template: "{{ states('media_player.alexa_kitchen_1') in ['playing'] }}"
  - condition: template
    value_template: "{{ states('media_player.alexa_downstairs') not in ['playing'] }}"
  - condition: template
    value_template: "{{ states('media_player.alexa_everywhere') not in ['playing'] }}"
  action:
  - service: script.turn_on
    entity_id:
      - script.beneden_music_play

- alias: Muziek - Downstairs - Play 1
  trigger:
  - platform: state
    entity_id: binary_sensor.hue_sensor_woonkamer_motion
    from: 'off'
    to: 'on'
  condition:
  - condition: time
    after: !secret radio_on
    before: !secret radio_off
  - condition: state
    entity_id: input_boolean.music_follow
    state: 'on'
  - condition: state
    entity_id: input_boolean.media_kitchen
    state: 'off'
  - condition: state
    entity_id: input_boolean.media_livingroom
    state: 'off'
  - condition: template
    value_template: "{{ states('input_select.woning_status') in ['Juist Thuis', 'Juist Wakker', 'Thuis', 'Thuis (Werk)', 'Thuis (Verlof)'] }}"
  - condition: template
    value_template: "{{ states('input_select.harmony_hub') in ['Powered Off', 'Alexa'] }}"
  - condition: template
    value_template: "{{ states('media_player.alexa_livingroom_1') not in ['playing'] }}"
  - condition: template
    value_template: "{{ states('media_player.alexa_downstairs') not in ['playing'] }}"
  - condition: template
    value_template: "{{ states('media_player.alexa_everywhere') not in ['playing'] }}"
  action:
  - delay: '00:02:00'
  - condition: template
    value_template: "{{ states('input_select.harmony_hub') in ['Powered Off', 'Alexa'] }}"
  - service: script.turn_on
    entity_id:
      - script.beneden_music_play

# PLAY RADIO IN LIVING ROOM

- alias: Muziek - Woonkamer - Play
  trigger:
  - platform: state
    entity_id: input_select.harmony_hub
  condition:
  - condition: template
    value_template: "{{ (states('media_player.alexa_livingroom_1') in ['playing'] and states('input_select.harmony_hub') not in ['Alexa']) or (states('media_player.alexa_livingroom_1') not in ['playing'] and states('media_player.alexa_downstairs') not in ['playing'] and states('media_player.alexa_everywhere') not in ['playing'] and states('input_select.harmony_hub') in ['Alexa']) }}"
  action:
  - service: script.turn_on
    data_template:
      entity_id: >
        {%- if states('media_player.alexa_livingroom_1') not in ['playing'] and states('media_player.alexa_downstairs') not in ['playing'] and states('media_player.alexa_everywhere') not in ['playing'] and states('input_select.harmony_hub') in ['Alexa'] -%}
          script.woonkamer_music_play
        {%- elif states('media_player.alexa_livingroom_1') in ['playing'] and states('input_select.harmony_hub') not in ['Alexa'] -%}
          script.woonkamer_music_stop
        {%- else -%}
          script.empty
        {%- endif %}

- alias: Muziek - Woonkamer - Stop
  trigger:
  - entity_id: binary_sensor.hue_sensor_woonkamer_motion
    for:
      minutes: 30
    platform: state
    to: 'off'
  - platform: time
    at: !secret radio_off
  condition:
  - condition: template
    value_template: "{{ states('media_player.alexa_livingroom_1') in ['playing'] }}"
  action:
  - service: script.turn_on
    data_template:
      entity_id: >
        {%- if states('media_player.alexa_downstairs') in ['playing'] -%}
          script.beneden_music_stop
        {%- elif states('media_player.alexa_downstairs') not in ['playing'] -%}
          script.woonkamer_music_stop
        {%- else -%}
          script.empty
        {%- endif %}

# PLAY RADIO IN BATHROOM

- alias: Muziek - Badkamer - Play
  trigger:
  - entity_id: binary_sensor.hue_sensor_dressing_motion
    platform: state
    from: 'off'
    to: 'on'
  condition:
  - condition: time
    after: !secret radio_on
    before: !secret radio_off
  - condition: state
    entity_id: input_boolean.music_follow
    state: 'on'
  - condition: template
    value_template: "{{ states('input_select.woning_status') in ['Juist Wakker', 'Thuis', 'Thuis (Werk)', 'Thuis (Verlof)'] }}"
  - condition: template
    value_template: "{{ states('media_player.alexa_bathroom') not in ['playing'] }}"
  - condition: template
    value_template: "{{ states('media_player.alexa_everywhere') not in ['playing'] }}"
  action:
  - service: script.turn_on
    entity_id:
      - script.badkamer_music_play

- alias: Muziek - Badkamer - Stop
  trigger:
  - entity_id: binary_sensor.hue_sensor_dressing_motion
    for:
      minutes: 30
    platform: state
    to: 'off'
  condition:
  - condition: template
    value_template: "{{ states('media_player.alexa_bathroom') in ['playing'] }}"
  action:
  - service: script.turn_on
    entity_id:
      - script.badkamer_music_stop

# PLAY RADIO IN KITCHEN

- alias: Muziek - Keuken - Play
  trigger:
  - platform: state
    entity_id:
      - input_boolean.media_kitchen
    to: 'off'
    for:
      minutes: 3
  - platform: template
    value_template: "{{ states('input_select.harmony_hub') in ['Powered Off', 'Alexa'] }}"
  - platform: state
    entity_id: binary_sensor.hue_sensor_keuken_motion
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: input_boolean.music_follow
    from: 'off'
    to: 'on'
  condition:
  - condition: time
    after: !secret radio_on
    before: !secret radio_off
  - condition: state
    entity_id: binary_sensor.hue_sensor_keuken_motion
    state: 'on'
  - condition: state
    entity_id: input_boolean.music_follow
    state: 'on'
  - condition: state
    entity_id: input_boolean.media_kitchen
    state: 'off'
  - condition: state
    entity_id: input_boolean.media_livingroom
    state: 'off'
  - condition: template
    value_template: "{{ states('input_select.woning_status') in ['Juist Thuis', 'Juist Wakker', 'Thuis', 'Thuis (Werk)', 'Thuis (Verlof)'] }}"
  - condition: template
    value_template: "{{ states('input_select.harmony_hub') in ['Powered Off', 'Alexa'] }}"
  - condition: template
    value_template: "{{ states('media_player.alexa_kitchen_1') not in ['playing'] }}"
  - condition: template
    value_template: "{{ states('media_player.alexa_downstairs') not in ['playing'] }}"
  - condition: template
    value_template: "{{ states('media_player.alexa_everywhere') not in ['playing'] }}"
  action:
  - service: script.turn_on
    entity_id:
      - script.keuken_music_play
  - delay: '00:10:00'

- alias: Muziek - Keuken - Stop
  trigger:
  - entity_id: binary_sensor.hue_sensor_keuken_motion
    for:
      minutes: 60
    platform: state
    to: 'off'
  - platform: template
    value_template: "{{ states('input_select.harmony_hub') in ['Tv Decoder', 'Web OS'] }}"
  - platform: state
    entity_id:
      - input_boolean.media_kitchen
      - input_boolean.media_livingroom
    to: 'on'
  - platform: state
    entity_id:
      - media_player.apple_tv_keuken
      - media_player.apple_tv_woonkamer
    to: 'playing'
  condition:
  - condition: state
    entity_id: input_boolean.music_follow
    state: 'on'
  - condition: template
    value_template: "{{ states('media_player.alexa_kitchen_1') in ['playing'] }}"
  action:
  - service: script.turn_on
    entity_id:
      - script.keuken_music_stop

# TEMPORARY DISABLE MUSIC FOLLOW

- alias: Muziek - Follow - Disable
  trigger:
  - entity_id: media_player.alexa_kitchen_1
    platform: state
    from: 'playing'
    to: 'paused'
  condition:
  - condition: or
    conditions:
      - condition: state
        entity_id: media_player.alexa_downstairs
        state: 'paused'
        for:
          minutes: 5
      - condition: state
        entity_id: media_player.alexa_downstairs
        state: 'standby'
        for:
          minutes: 5
      - condition: state
        entity_id: media_player.alexa_downstairs
        state: 'unavailable'
        for:
          minutes: 5
  - condition: state
    entity_id: input_boolean.music_follow
    state: 'on'
  - condition: state
    entity_id: input_boolean.media_kitchen
    state: 'off'
  - condition: state
    entity_id: input_boolean.media_livingroom
    state: 'off'
  - condition: template
    value_template: "{{ states('input_select.harmony_hub') in ['Powered Off'] }}"
  - condition: template
    value_template: "{{ states('input_select.woning_status') not in ['Juist Weg', 'Weg', 'Slapen'] }}"
  action:
    - service: script.turn_on
      entity_id:
        - script.music_follow_off
        - script.keuken_music_stop

- alias: Muziek - Follow - Enable
  trigger:
  - entity_id: media_player.alexa_kitchen_1
    platform: state
    from: 'paused'
    to: 'playing'
  - entity_id: media_player.alexa_downstairs
    platform: state
    from: 'paused'
    to: 'playing'
  - entity_id: media_player.alexa_livingroom_1
    platform: state
    from: 'paused'
    to: 'playing'
  - entity_id: input_boolean.music_follow
    platform: state
    to: 'off'
    for:
      minutes: 4
  condition:
  - condition: or
    conditions:
      - condition: state
        entity_id: media_player.alexa_kitchen_1
        state: 'playing'
      - condition: state
        entity_id: media_player.alexa_downstairs
        state: 'playing'
      - condition: state
        entity_id: media_player.alexa_livingroom_1
        state: 'playing'
  - condition: state
    entity_id: input_boolean.music_follow
    state: 'off'
    for:
      minutes: 3
  action:
  - service: script.turn_on
    entity_id:
      - script.music_follow_on

- alias: Muziek - Follow - Enable 2
  trigger:
  - entity_id: input_boolean.music_follow
    platform: state
    to: 'off'
    for:
      minutes: 180
  action:
  - service: script.turn_on
    entity_id:
      - script.music_follow_on

# RADIO VOLUME

- alias: Muziek - Volume - Woonkamer
  trigger:
  - platform: template
    value_template: "{{ states('input_select.harmony_hub') in ['Alexa'] }}"
  - platform: state
    to: 'playing'
    entity_id:
      - media_player.alexa_livingroom_1
      - media_player.alexa_downstairs
      - media_player.alexa_everywhere
  action:
  - service: script.turn_on
    entity_id:
      - script.woonkamer_music_volume

- alias: Muziek - Volume - Beiden Thuis
  trigger:
  - platform: state
    to: home
    entity_id:
      - person.bert
      - person.caroline
  condition:
  - condition: state
    entity_id: person.bert
    state: 'home'
  - condition: state
    entity_id: person.caroline
    state: 'home'
  action:
  - service: script.turn_on
    entity_id:
      - script.keuken_music_volume
      - script.woonkamer_music_volume
      - script.badkamer_music_volume

- alias: Muziek - Volume - Keuken Ochtend
  trigger:
  - platform: time
    at: '07:59:00'
  - platform: time
    at: '08:59:00'
  condition:
  - condition: template
    value_template: "{{ states('media_player.alexa_kitchen_1') in ['playing'] and states('input_select.woning_status') in ['Thuis', 'Thuis (Werk)', 'Thuis (Verlof)'] }}"
  action:
  - service: script.turn_on
    entity_id: script.keuken_music_volume

- alias: Muziek - Volume - Woonkamer Nieuws
  trigger:
  - platform: time
    at: '19:00:00'
  condition:
  - condition: template
    value_template: "{{ (states('media_player.alexa_livingroom_1') in ['playing'] and states('input_select.harmony_hub') in ['Alexa']) }}"
  action:
  - service: script.turn_on
    entity_id: script.woonkamer_music_volume