# AUTOMATION AMPLIFIER LIVING ROOM

- alias: Amplifier Woonkamer - Uit - Apple TV Not Playing
  trigger:
    - platform: template
      value_template: "{{ states('media_player.apple_tv_woonkamer') in ['idle', 'paused'] }}"
      for:
        minutes: 30
  condition:
    - condition: template
      value_template: "{{ states('input_select.harmony_hub') in ['Apple Tv'] }}"
    - condition: template
      value_template: "{{ states('media_player.apple_tv_woonkamer') in ['paused', 'idle'] }}"
  action:
    - service: script.turn_on
      entity_id: script.harmony_hub_powered_off

- alias: Amplifier Woonkamer - Uit - Echo Not Playing
  trigger:
    - platform: template
      value_template: "{{ states('media_player.alexa_livingroom_1') not in ['playing'] }}"
      for:
        minutes: 5
    - platform: template
      value_template: "{{ states('media_player.alexa_everywhere') not in ['playing'] }}"
      for:
        minutes: 5
    - platform: template
      value_template: "{{ states('media_player.alexa_downstairs') not in ['playing'] }}"
      for:
        minutes: 5
  condition:
    - condition: template
      value_template: "{{ states('media_player.alexa_livingroom_1') not in ['playing'] }}"
    - condition: template
      value_template: "{{ states('media_player.alexa_downstairs') not in ['playing'] }}"
    - condition: template
      value_template: "{{ states('media_player.alexa_everywhere') not in ['playing'] }}"
    - condition: template
      value_template: "{{ states('input_select.harmony_hub') in ['Alexa'] }}"
  action:
    - service: script.turn_on
      entity_id: script.harmony_hub_powered_off

- alias: Amplifier Woonkamer - Aan - Echo Playing
  trigger:
    - platform: state
      entity_id: 
        - media_player.alexa_livingroom_1
        - media_player.alexa_everywhere
        - media_player.alexa_downstairs
      to: playing
  condition:
    - condition: state
      entity_id: input_select.harmony_hub
      state: 'Powered Off'
  action:
    - service: script.turn_on
      entity_id: script.harmony_hub_alexa

- alias: Amplifier Woonkamer - Aan - Echo Playing (Harmony Powered Off)
  trigger:
    - platform: state
      entity_id: input_select.harmony_hub
      to: 'Powered Off'
      for:
        minutes: 3
  condition:
    - condition: template
      value_template: "{{ states('input_select.woning_status') in ['Juist Thuis', 'Thuis', 'Thuis (Werk)', 'Thuis (Verlof)', 'Juist Wakker'] }}"
    - condition: or
      conditions:
      - condition: state
        entity_id: media_player.alexa_everywhere
        state: playing
      - condition: state
        entity_id: media_player.alexa_livingroom_1
        state: playing
      - condition: state
        entity_id: media_player.alexa_downstairs
        state: playing
  action:
    - delay: 00:00:05
    - service: script.turn_on
      entity_id: script.harmony_hub_alexa

# AUTOMATION AMPLIFIER KITCHEN

- alias: Amplifier Keuken - Aan - Echo Playing
  trigger:
    - platform: state
      entity_id: 
        - media_player.alexa_kitchen_1
        - media_player.alexa_everywhere
        - media_player.alexa_downstairs
      to: playing
  condition:
    - condition: state
      entity_id: light.hue_smart_plug_keuken
      state: 'off'
  action:
    - service: script.turn_on
      entity_id:
        - script.hue_smart_plug_kitchen_on

- alias: Amplifier Keuken - Uit - Echo Not Playing
  trigger:
    - platform: template
      value_template: "{{ states('media_player.alexa_kitchen_1') not in ['playing'] }}"
      for:
        minutes: 2
    - platform: template
      value_template: "{{ states('media_player.alexa_everywhere') not in ['playing'] }}"
      for:
        minutes: 2
    - platform: template
      value_template: "{{ states('media_player.alexa_downstairs') not in ['playing'] }}"
      for:
        minutes: 2
  condition:
    - condition: state
      entity_id: light.hue_smart_plug_keuken
      state: 'on'
    - condition: template
      value_template: "{{ states('media_player.alexa_everywhere') not in ['playing'] }}"
    - condition: template
      value_template: "{{ states('media_player.alexa_downstairs') not in ['playing'] }}"
    - condition: template
      value_template: "{{ states('media_player.alexa_kitchen_1') not in ['playing'] }}"
  action:
    - service: script.turn_on
      entity_id:
        - script.hue_smart_plug_kitchen_off