# AUTOMATION AMPLIFIER LIVING ROOM

- alias: Amplifier Woonkamer - Uit - Apple TV Not Playing
  trigger:
    - platform: state
      entity_id: media_player.apple_tv_woonkamer
      to: 'idle'
      for:
        minutes: 30
    - platform: state
      entity_id: media_player.apple_tv_woonkamer
      to: 'paused'
      for:
        minutes: 30
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: input_select.harmony_hub
      state: 'Apple Tv'
    - condition: or
      conditions:
      - condition: state
        entity_id: media_player.apple_tv_woonkamer
        state: 'idle'
      - condition: state
        entity_id: media_player.apple_tv_woonkamer
        state: 'paused'
  action:
    - service: input_select.select_option
      entity_id: input_select.harmony_hub
      data:
        option: "Powered Off"

- alias: Amplifier Woonkamer - Uit - Echo Not Playing
  trigger:
    - platform: state
      entity_id: media_player.livingroom_alexa
      to: paused
      for:
        minutes: 5
    - platform: state
      entity_id: media_player.everywhere
      to: paused
      for:
        minutes: 5
    - platform: state
      entity_id: media_player.downstairs
      to: paused
      for:
        minutes: 5
    - platform: state
      entity_id: media_player.livingroom_alexa
      to: standby
      for:
        minutes: 5
    - platform: state
      entity_id: media_player.everywhere
      to: standby
      for:
        minutes: 5
    - platform: state
      entity_id: media_player.downstairs
      to: standby
      for:
        minutes: 5
  condition:
    condition: or
    conditions:
      - condition: and
        conditions:
        - condition: state
          entity_id: input_select.harmony_hub
          state: 'Alexa'
        - condition: state
          entity_id: media_player.everywhere
          state: 'paused'
        - condition: state
          entity_id: media_player.downstairs
          state: 'paused'
        - condition: state
          entity_id: media_player.livingroom_alexa
          state: 'paused'
      - condition: and
        conditions:
        - condition: state
          entity_id: input_select.harmony_hub
          state: 'Alexa'
        - condition: state
          entity_id: media_player.everywhere
          state: 'standby'
        - condition: state
          entity_id: media_player.downstairs
          state: 'standby'
        - condition: state
          entity_id: media_player.livingroom_alexa
          state: 'standby'
      - condition: and
        conditions:
        - condition: state
          entity_id: input_select.harmony_hub
          state: 'Alexa'
        - condition: state
          entity_id: media_player.everywhere
          state: 'paused'
        - condition: state
          entity_id: media_player.downstairs
          state: 'paused'
        - condition: state
          entity_id: media_player.livingroom_alexa
          state: 'standby'
      - condition: and
        conditions:
        - condition: state
          entity_id: input_select.harmony_hub
          state: 'Alexa'
        - condition: state
          entity_id: media_player.everywhere
          state: 'paused'
        - condition: state
          entity_id: media_player.downstairs
          state: 'standby'
        - condition: state
          entity_id: media_player.livingroom_alexa
          state: 'paused'
      - condition: and
        conditions:
        - condition: state
          entity_id: input_select.harmony_hub
          state: 'Alexa'
        - condition: state
          entity_id: media_player.everywhere
          state: 'standby'
        - condition: state
          entity_id: media_player.downstairs
          state: 'paused'
        - condition: state
          entity_id: media_player.livingroom_alexa
          state: 'paused'
      - condition: and
        conditions:
        - condition: state
          entity_id: input_select.harmony_hub
          state: 'Alexa'
        - condition: state
          entity_id: media_player.everywhere
          state: 'paused'
        - condition: state
          entity_id: media_player.downstairs
          state: 'standby'
        - condition: state
          entity_id: media_player.livingroom_alexa
          state: 'standby'
      - condition: and
        conditions:
        - condition: state
          entity_id: input_select.harmony_hub
          state: 'Alexa'
        - condition: state
          entity_id: media_player.everywhere
          state: 'standby'
        - condition: state
          entity_id: media_player.downstairs
          state: 'paused'
        - condition: state
          entity_id: media_player.livingroom_alexa
          state: 'standby'
      - condition: and
        conditions:
        - condition: state
          entity_id: input_select.harmony_hub
          state: 'Alexa'
        - condition: state
          entity_id: media_player.everywhere
          state: 'standby'
        - condition: state
          entity_id: media_player.downstairs
          state: 'standby'
        - condition: state
          entity_id: media_player.livingroom_alexa
          state: 'paused'
  action:
    - service: input_select.select_option
      entity_id: input_select.harmony_hub
      data:
        option: "Powered Off"

- alias: Amplifier Woonkamer - Aan - Echo Playing
  trigger:
    - platform: state
      entity_id: media_player.livingroom_alexa
      to: playing
    - platform: state
      entity_id: media_player.everywhere
      to: playing
    - platform: state
      entity_id: media_player.downstairs
      to: playing
  condition:
    - condition: state
      entity_id: input_select.harmony_hub
      state: 'Powered Off'
  action:
    - service: input_select.select_option
      entity_id: input_select.harmony_hub
      data:
        option: "Alexa"

- alias: Amplifier Woonkamer - Aan - Echo Playing (Harmony Powered Off)
  trigger:
    - platform: state
      entity_id: input_select.harmony_hub
      to: 'Powered Off'
      for:
        minutes: 3
  condition:
    condition: and
    conditions:
      - condition: or
        conditions:
        - condition: state
          entity_id: input_select.woning_status
          state: 'Thuis'
        - condition: state
          entity_id: input_select.woning_status
          state: 'Juist Thuis'
        - condition: state
          entity_id: input_select.woning_status
          state: 'Thuis (Werk)'
        - condition: state
          entity_id: input_select.woning_status
          state: 'Thuis (Verlof)'
        - condition: state
          entity_id: input_select.woning_status
          state: 'Juist Wakker'
      - condition: or
        conditions:
        - condition: state
          entity_id: media_player.everywhere
          state: playing
        - condition: state
          entity_id: media_player.livingroom_alexa
          state: playing
        - condition: state
          entity_id: media_player.downstairs
          state: playing
  action:
    - delay: 00:00:05
    - service: input_select.select_option
      entity_id: input_select.harmony_hub
      data:
        option: "Alexa"

# AUTOMATION AMPLIFIER KITCHEN

- alias: Amplifier Keuken - Aan - Echo Playing
  trigger:
    - platform: state
      entity_id: media_player.kitchen_alexa_1
      to: playing
    - platform: state
      entity_id: media_player.everywhere
      to: playing
    - platform: state
      entity_id: media_player.downstairs
      to: playing
  condition:
    - condition: state
      entity_id: light.hue_keuken_smart_plug
      state: 'off'
  action:
    - service: script.turn_on
      entity_id:
        - script.switch_kitchen_speakers_on

- alias: Amplifier Keuken - Uit - Echo Not Playing
  trigger:
    - platform: state
      entity_id: media_player.kitchen_alexa_1
      to: paused
      for:
        minutes: 2
    - platform: state
      entity_id: media_player.everywhere
      to: paused
      for:
        minutes: 2
    - platform: state
      entity_id: media_player.downstairs
      to: paused
      for:
        minutes: 2
    - platform: state
      entity_id: media_player.kitchen_alexa_1
      to: standby
      for:
        minutes: 2
    - platform: state
      entity_id: media_player.everywhere
      to: standby
      for:
        minutes: 2
    - platform: state
      entity_id: media_player.downstairs
      to: standby
      for:
        minutes: 2
  condition:
    - condition: state
      entity_id: light.hue_keuken_smart_plug
      state: 'on'
    - condition: and
      conditions:
      - condition: template
        value_template: "{{ states('media_player.everywhere') not in ['playing'] }}"
      - condition: template
        value_template: "{{ states('media_player.downstairs') not in ['playing'] }}"
      - condition: template
        value_template: "{{ states('media_player.kitchen_alexa_1') not in ['playing'] }}"
  action:
    - service: script.turn_on
      entity_id:
        - script.switch_kitchen_speakers_off