- alias: Batterij - Smappee - Bijna Leeg
  trigger:
  - entity_id: sensor.smappee_ons_huisje_water_sensor_battery
    below: '20'
    platform: numeric_state
  - entity_id: sensor.smappee_ons_huisje_water_sensor_battery
    below: '10'
    platform: numeric_state
  - entity_id: sensor.smappee_ons_huisje_water_sensor_battery
    below: '5'
    platform: numeric_state
  action:
  - service: script.turn_on
    data:
      entity_id: script.notify_battery
