# AUTOMATIONS TO NOTIFY WHEN VISITOR ARRIVES

- alias: Bezoeker - Thuis of Weg
  initial_state: 'off'
  trigger:
  - platform: state
    entity_id:
      - person.mark
      - person.mama
      - person.andy
      - person.karen
      - person.marcus
      - person.niki
      - person.oma
      - person.nancy
      - person.thomas
      - person.papa
    from: "home"
    to: "not_home"
  - platform: state
    entity_id:
      - person.mark
      - person.mama
      - person.andy
      - person.karen
      - person.marcus
      - person.niki
      - person.oma
      - person.nancy
      - person.thomas
      - person.papa
    from: "not_home"
    to: "home"
  condition:
  action:
  - service: script.notify_tracker_bezoeker_thuis_ios_bert
    data_template:
      bezoeker: '{{ trigger.to_state.attributes.friendly_name }}'
      bezoeker_state: '{{ trigger.to_state.state }}'
  - service: script.notify_tracker_bezoeker_thuis_ios_caro
    data_template:
      bezoeker: '{{ trigger.to_state.attributes.friendly_name }}'
      bezoeker_state: '{{ trigger.to_state.state }}'
  - service: script.notify_tracker_bezoeker_thuis_alexa
    data_template:
      bezoeker: '{{ trigger.to_state.attributes.friendly_name }}'
      bezoeker_state: '{{ trigger.to_state.state }}'

- alias: Bezoeker - Babysit - Aangekomen
  trigger:
  - platform: state
    entity_id: calendar.babysit_agenda
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.visitor
    state: 'off'
  action:
  - service: input_boolean.turn_on
    entity_id:
      - input_boolean.visitor

- alias: Bezoeker - Babysit - Vertrokken
  trigger:
  - platform: state
    entity_id: calendar.babysit_agenda
    to: 'off'
  condition:
  - condition: state
    entity_id: input_boolean.visitor
    state: 'off'
  action:
  - service: script.turn_on
    entity_id:
      - script.notify_bezoeker_babysit_ios_caro
      - script.notify_bezoeker_babysit_ios_bert

- alias: Bezoeker - Babysit - Blijft
  trigger:
  - platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: LEAVE_VISITOR
  condition:
  - condition: state
    entity_id: input_boolean.visitor
    state: 'off'
  action:
  - service: input_boolean.turn_on
    entity_id:
      - input_boolean.visitor

- alias: Bezoeker - Babysit - Gaat Weg
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: RESET_VISITOR
  action:
  - service: input_boolean.turn_off
    entity_id:
      - input_boolean.visitor
