# AUTOMATIONS TO NOTIFY WHEN VISITOR ARRIVES

- alias: Bezoeker - Thuis of Weg
  initial_state: 'off'
  trigger:
  - platform: state
    entity_id:
      - person.mark
      - person.mama
      - person.andy
      - person.karen
      - person.marcus
      - person.niki
      - person.oma
      - person.nancy
      - person.thomas
      - person.papa
  condition:
  action:
  - service: script.notify_tracker_bezoeker_thuis_ios_bert
    data_template:
      bezoeker: '{{ trigger.to_state.attributes.friendly_name }}'
      bezoeker_state: '{{ trigger.to_state.state }}'
  - service: script.notify_tracker_bezoeker_thuis_ios_caro
    data_template:
      bezoeker: '{{ trigger.to_state.attributes.friendly_name }}'
      bezoeker_state: '{{ trigger.to_state.state }}'
  - service: script.notify_tracker_bezoeker_thuis_alexa
    data_template:
      bezoeker: '{{ trigger.to_state.attributes.friendly_name }}'
      bezoeker_state: '{{ trigger.to_state.state }}'
