# AUTOMATIONS BASED ON GOOGLE CAST

- alias: Cast - Kitchen - Start
  trigger:
  - platform: state
    entity_id: media_player.chromecast_kitchen
    to: 'off'
  action:
   - service: cast.show_lovelace_view
     data:
       entity_id: media_player.chromecast_kitchen
       view_path: "google_cast"
