# AUTOMATIONS WHEN DOORBEL IS PRESSED

- alias: Deurbel - Als Deurbel Gaat
  trigger:
  - platform: state
    entity_id: binary_sensor.deurbel_voor_button
    to: 'on'
  condition:
  action:
  - service: script.turn_on
    entity_id:
      - script.notify_deurbel
      - script.all_remote_harmony_hub_pause

# AUTOMATIONS CHIME ACTIVE/ NOT ACTIVE

- alias: Deurbel - Als Arlo On
  trigger:
  - platform: state
    entity_id: light.aarlo_arlobaby
    to: 'on'
  condition:
  action:
  - service: script.turn_on
    entity_id:
      - script.doorbell_chime_off

- alias: Deurbel - Als Arlo Off
  trigger:
  - platform: state
    entity_id: light.aarlo_arlobaby
    to: 'off'
  condition:
  action:
  - service: script.turn_on
    entity_id:
      - script.doorbell_chime_on