# AUTOMATIONS FOR RESTARTING HOME ASSISTANT (ACTION = SCRIPT)

- alias: Hassio - Restart Check
  trigger:
  - event: start
    platform: homeassistant
  action:
  - delay: 00:00:30
  - service: script.turn_on
    entity_id:
      - script.restart_hassio
      - script.restart_homekit
      - script.restart_homekit_not

# NOTIFY WHEN UPDATE AVAILABLE

- alias: Hassio - Update Available
  initial_state: 'off'
  trigger:
  - platform: state
    entity_id: binary_sensor.updater
    to: 'on'
  action:
  - service: script.turn_on
    data:
      entity_id: script.notify_hassio_update

- alias: Hassio - Update Available HACS
  initial_state: 'off'
  trigger:
  - platform: numeric_state
    entity_id: sensor.hacs
    above: '0'
  action:
  - service: script.turn_on
    data:
      entity_id: script.notify_hacs_update

# NOTIFY WHEN SERVER SPEED MAXED

- alias: Hassio - Volle toeren
  trigger:
  - platform: numeric_state
    entity_id:
      - sensor.memory_use_percent
      - sensor.disk_use_percent_home
      - sensor.processor_use
    above: '90'
  action:
  - service: script.turn_on
    data:
      entity_id: script.notify_hassio_overtime
