# AUTOMATION VACUUM - ROOMBA

- alias: Vacuum Dennis - Notify - Status Dennis Changes
  initial_state: 'off'
  trigger:
  - platform: template
    value_template: "{{ state_attr('vacuum.dennis', 'bin_full') == true }}"
  - platform: template
    value_template: "{{ state_attr('vacuum.dennis', 'status') == Stuck }}"
  - platform: state
    entity_id:
      - vacuum.dennis
    to: 'off'
  - platform: state
    entity_id:
      - vacuum.dennis
    to: 'on'
  condition:
  action:
  - service: script.turn_on
    entity_id:
      - script.notify_vacuum

- alias: Vacuum Dennis - Notify - Status Woning Changes
  initial_state: 'off'
  trigger:
  - platform: state
    entity_id: input_select.woning_status
    from: 'Juist Thuis'
    to: 'Thuis'
  - platform: state
    entity_id: input_select.woning_status
    from: 'Juist Thuis'
    to: 'Thuis (Werk)'
  - platform: state
    entity_id: input_select.woning_status
    from: 'Juist Thuis'
    to: 'Thuis (Verlof)'
  condition:
  action:
  - service: script.turn_on
    entity_id:
      - script.notify_vacuum

- alias: Vacuum Dennis - Cleaned Today
  trigger:
  - platform: state
    entity_id:
      - vacuum.dennis
    to: 'on'
    for:
      minutes: 55
  condition:
  - condition: state
    entity_id: input_boolean.vacuum_cleaned_today
    state: 'off'
  action:
  - service: input_boolean.turn_on
    entity_id:
      - input_boolean.vacuum_cleaned_today

- alias: Vacuum Dennis - Cleaned Today - Kuishulp
  trigger:
  - platform: state
    entity_id: calendar.kuishulp_agenda
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.vacuum_cleaned_today
    state: 'off'
  action:
  - service: input_boolean.turn_on
    entity_id:
      - input_boolean.vacuum_cleaned_today

- alias: Vacuum Dennis - Cleaned Today - Reset
  trigger:
  - platform: time
    at: '23:59:00'
  condition:
  - condition: state
    entity_id: input_boolean.vacuum_cleaned_today
    state: 'on'
  action:
  - service: input_boolean.turn_off
    entity_id:
      - input_boolean.vacuum_cleaned_today

- alias: Vacuum Dennis - Start when lux enough
  trigger:
  - platform: numeric_state
    entity_id: sensor.hue_sensor_keuken_light_level
    above: !secret lux_kitchen_very_very_low
    for:
      minutes: 4
  condition:
  - condition: template
    value_template: "{{ states('input_select.woning_status') in ['Juist Weg', 'Weg'] }}"
  - condition: template
    value_template: "{{ states('vacuum.dennis') in ['off'] }}"
  - condition: state
    entity_id: input_boolean.vacuum_cleaned_today
    state: 'off'
  - condition: time
    after: !secret work_week_start
    before: !secret work_week_mid
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
  - service: script.turn_on
    entity_id: script.dennis_on

# AUTOMATION PRINTER

- alias: Printer - Notify - Ink Low
  initial_state: 'off'
  trigger:
  - platform: numeric_state
    entity_id: sensor.hp_deskjet_3700_series_black_ink
    below: 25
  - platform: numeric_state
    entity_id: sensor.hp_deskjet_3700_series_tri_color_ink
    below: 25
  - platform: numeric_state
    entity_id: sensor.hp_deskjet_3700_series_black_ink
    below: 10
  - platform: numeric_state
    entity_id: sensor.hp_deskjet_3700_series_tri_color_ink
    below: 10
  condition:
  action:
  - service: script.turn_on
    entity_id:
      - script.notify_printer