# AUTOMATIONS WHEN WASTE NEEDS TO BE OUTSIDE CHANGES

- alias: Vuilbakken - Reminder voor avond
  trigger:
  - platform: time
    at: '20:30:00'
  condition:
  - condition: template
    value_template: "{{ states('input_select.woning_status') in ['Juist Thuis', 'Thuis', 'Dag Thuis'] }}"
  action:
  - service: script.turn_on
    entity_id: script.notify_waste

- alias: Vuilbakken - Status Woning Changes
  trigger:
  - platform: state
    entity_id: input_select.woning_status
    from: 'Juist Thuis'
    to: 'Thuis'
  - platform: state
    entity_id: input_select.woning_status
    from: 'Juist Thuis'
    to: 'Dag Thuis'
  condition:
  action:
  - service: script.turn_on
    entity_id: script.notify_waste

- alias: Vuilbakken - Bert Thuis
  trigger:
  - platform: state
    entity_id: person.bert
    to: 'home'
  condition:
  - condition: template
    value_template: "{{ states('input_select.woning_status') in ['Thuis', 'Dag Thuis'] }}"
  action:
  - wait_template: "{{ is_state('device_tracker.router_iphone_bert', 'home') }}"
    timeout: '00:05:00'
    continue_on_timeout: false
  - service: script.turn_on
    entity_id: script.notify_waste_ios_bert
